### ISSUE TITLE
Telethon Error : Flood Wait Error 

### ISSUE THREAD

**Issue by karniv0re-cyber** [expectocode/telegram-export#122]
When I Execute the tool : 
`python3 telegram_export `

It first logged in and when I executed the command again, it throws the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "telegram_export/__main__.py", line 316, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "telegram_export/__main__.py", line 289, in main
    ).start(config['TelegramAPI']['PhoneNumber']))
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 148, in _start
    sent_code = await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 374, in send_code_request
    phone, self.api_id, self.api_hash))
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 60, in __call__
    result = await future
**telethon.errors.rpcerrorlist.FloodWaitError: A wait of 77264 seconds is required (caused by SendCodeRequest)**

Please let me know a solution. Thank you.

![Capture](https://user-images.githubusercontent.com/54171256/63420614-afdeed00-c424-11e9-9f68-8cce1b571384.PNG)

**Comment by shinji257** [comment]
I'm hitting into this same issue when using my own API code.  Didn't even get to login.
