### ISSUE TITLE
Use telethon-asyncio as a dependency, not telethon

### ISSUE THREAD

**Issue by nobody16** [expectocode/telegram-export#24]
With telethon 0.15 and bigger:

Traceback (most recent call last):
  File "telegram_export.py", line 289, in <module>
    ret = loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "telegram_export.py", line 245, in main
    config['TelegramAPI']['ApiHash']
AttributeError: 'TelegramClient' object has no attribute 'start'

With 0.13:

Traceback (most recent call last):
  File "telegram_export.py", line 17, in <module>
    from dumper import Dumper
  File "/video/backup_telegram/telegram-export/dumper.py", line 15, in <module>
    from telethon.utils import get_peer_id, resolve_id, get_input_peer
ImportError: cannot import name 'get_peer_id'

With 0.17.4.5

Traceback (most recent call last):
  File "telegram_export.py", line 289, in <module>
    ret = loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "telegram_export.py", line 246, in main
    ).start(config['TelegramAPI']['PhoneNumber'])
TypeError: object TelegramClient can't be used in 'await' expression

**Comment by Lonami** [comment]
We're pretty much daily working on both projects and currently both get updates very quickly. Needless to say we won't support old versions because we would lose some nice features, additions and bug fixes on the library (which isn't `v1.0` in itself yet). Please upgrade to the latest `v0.17.x` and try again.

**Comment by nobody16** [comment]
Sorry, my mistake I not put my error with last version

**Comment by Lonami** [comment]
Okay, I see. We're using the `asyncio` branch of Telethon with the latest changes. This simplifies quite a few things and avoids some problems with threading we had just a day ago. I'll keep this open until I publish the `asyncio` version of the library ln PyPi so I can remember!

**Comment by Lonami** [comment]
You can install Telethon-asyncio by running:
```
pip install --upgrade git+https://github.com/LonamiWebs/Telethon@asyncio
```

Don't hesitate to report any further bugs or issues you come accross :)

**Comment by nobody16** [comment]
Okey, danke. Fixed but now, newone.

/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:291: RuntimeWarning: coroutine 'TelegramClient._check_events_pending_resolve' was never awaited
  self._check_events_pending_resolve()
2018-03-03 22:26:51,842 - __main__ - INFO - Closing exporter
example: 0 messages [00:00, ? messages/s]Traceback (most recent call last):██████████████████████████████████████████████| 1/1 [00:00/00:00,  9.94 entities/s, chat=example]
  File "telegram_export.py", line 289, in <module>
    ret = loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "telegram_export.py", line 263, in main
    await downloader.start(who)
  File "/video/backup_telegram/telegram-export/downloader.py", line 420, in start
    max_id = self.dumper.get_message_id(target_id, 'MAX')
  File "/video/backup_telegram/telegram-export/dumper.py", line 591, in get_message_id
    """.format(which=which), (context_id,)).fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by Lonami** [comment]
Oops, that sounds like a different bug.

**Comment by expectocode** [comment]
The readme points to the asyncio branch of telethon as of 7383c76, but it would be better to use PyPI.

**Comment by Lonami** [comment]
You can now `pip install telethon-aio`. **Do not `pip install telethon-asyncio`**, I don't own that. Someone name-squatted it.
