### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by nobody16** [expectocode/telegram-export#28]
Hello again, I seen a lot of changes and I removed my session file (and all of the content), just because I see some error when I did a get pull and start again:

blaaaahhh: 717 messages [00:00, 547282.25 Traceback (most recent call last):
  File "./telegram_export.py", line 318, in <module>enturas [PALOMITAS]]
    ret = loop.run_until_complete(main()) or 0ALOMITAS]]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "./telegram_export.py", line 289, in main
    await downloader.start(entity)
  File "/video/backup_telegram/telegram-export/downloader.py", line 336, in start
    for media in self.dumper.iter_resume_media(target_id):
  File "/video/backup_telegram/telegram-export/dumper.py", line 695, in iter_resume_media
    "FROM ResumeMedia WHERE ContextID = ?", (context_id,)
sqlite3.OperationalError: no such table: ResumeMedia

After that the delete all the content, I can't start the app again:

python3 telegram_export.py
Traceback (most recent call last):
  File "telegram_export.py", line 318, in <module>
    ret = loop.run_until_complete(main()) or 0
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "telegram_export.py", line 269, in main
    ).start(config['TelegramAPI']['PhoneNumber'])
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_client.py", line 308, in start
    sent_code = await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_client.py", line 210, in send_code_request
    result = await self(SendCodeRequest(phone, self.api_id, self.api_hash))
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_bare_client.py", line 424, in __call__
    result = await self._invoke(call_receive, retry, *requests)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_bare_client.py", line 468, in _invoke
    await self._sender.send(*requests)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/network/mtproto_sender.py", line 110, in send
    await self._send_message(message)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/network/mtproto_sender.py", line 165, in _send_message
    await self.connection.send(utils.pack_message(self.session, message))
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/helpers.py", line 33, in pack_message
    data = struct.pack('<qq', session.salt, session.id) + bytes(message)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/tl/tl_message.py", line 25, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/tl/gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/tl/functions/auth.py", line 508, in __bytes__
    TLObject.serialize_bytes(self.phone_number),
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/tl/tlobject.py", line 98, in serialize_bytes
    'bytes or str expected, not {}'.format(type(data)))
TypeError: bytes or str expected, not <class 'NoneType'>

**Comment by expectocode** [comment]
@nobody16 Do you have your phone number in your config file?

**Comment by nobody16** [comment]
Yes, the config.file is still the same.

**Comment by nobody16** [comment]
Woa! Sorry, it was a quote problem again, I removed the quotes and now works..

**Comment by Lonami** [comment]
No problem, though we should probably .strip() those maybe.

**Comment by expectocode** [comment]
I don't think stripping quotes would be necessary - it's better to have a consistent set of rules throughout the file, and helpful error messages.
