### ISSUE TITLE
FloodWait when downloading media

### ISSUE THREAD

**Issue by nobody16** [expectocode/telegram-export#30]
Maybe you can catch this one:

2018-03-04 20:42:44,964 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<Downloader._media_consumer() done, defined at /video/backup_telegram/telegram-export/downloader.py:150> exception=FloodWaitError('A wait of 445 seconds is required',)>
Traceback (most recent call last):
  File "/video/backup_telegram/telegram-export/downloader.py", line 174, in _media_consumer
    progress_callback=progress
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_client.py", line 1956, in download_file
    input_location, offset, part_size
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_bare_client.py", line 424, in __call__
    result = await self._invoke(call_receive, retry, *requests)
  File "/usr/local/lib/python3.6/dist-packages/telethon_aio/telegram_bare_client.py", line 509, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon_aio.errors.rpc_error_list.FloodWaitError: A wait of 445 seconds is required

**Comment by Lonami** [comment]
Telegram is rather strict when it comes down to how many requests you can invoke in a certain period of time, so we add sleeps between them to avoid hitting them. However… seems like we haven't quite chosen the right sleep for downloading media. Incrementing it will make downloading media slower, but safer (in the sense of avoiding this flood).

**Comment by expectocode** [comment]
@nobody16 is the problem fixed now?

**Comment by expectocode** [comment]
Looks fixed to me.
