### ISSUE TITLE
TypeError: 'async for' requires an object with __aiter__ method, got coroutine

### ISSUE THREAD

**Issue by RaD** [expectocode/telegram-export#33]
Fail if try to repeat the script run next time:

```
$ telegram-export
2018-03-27 17:48:58,000 - telethon.telegram_bare_client - INFO - Connecting to 149.154.167.51:443...
2018-03-27 17:48:58,047 - telethon.telegram_bare_client - INFO - Connection success!
2018-03-27 17:48:58,048 - telethon.telegram_bare_client - INFO - Initializing a new connection while invoking
2018-03-27 17:48:58,161 - exporter - INFO - Saving to /Users/user/exports/chat
2018-03-27 17:48:58,163 - telethon.telegram_bare_client - INFO - Starting to wait for items from the network
customer: 9496 messages [00:00, 569.42 messages/s]
2018-03-27 17:48:58,585 - telegram_export.downloader - INFO - Done. Retrieving full information about 1 missing entities.
entities: 100%|***** | 2/2 [00:01<00:00,  1.89 entities/s, chat=customer]
media: 0.00B [00:00, ?B/s, chat=customer]
2018-03-27 17:49:04,421 - exporter - INFO - Closing exporter
2018-03-27 17:49:04,421 - telethon.telegram_bare_client - INFO - Disconnecting...
2018-03-27 17:49:04,421 - telethon.network.mtproto_sender - INFO - Disconnecting MtProtoSender...
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/mine/bin/telegram-export", line 3, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user/.virtualenvs/mine/lib/python3.6/site-packages/telegram_export/__main__.py", line 287, in <module>
    ret = loop.run_until_complete(main()) or 0
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/Users/user/.virtualenvs/mine/lib/python3.6/site-packages/telegram_export/__main__.py", line 271, in main
    await exporter.start()
  File "/Users/user/.virtualenvs/mine/lib/python3.6/site-packages/telegram_export/exporter.py", line 71, in start
    self.client):
  File "/Users/user/.virtualenvs/mine/lib/python3.6/site-packages/telegram_export/exporter.py", line 33, in get_entities_iter
    async for ent in entities_from_str(client, in_list):
  File "/Users/user/.virtualenvs/mine/lib/python3.6/site-packages/telegram_export/exporter.py", line 18, in entities_from_str
    yield await client.get_input_entity(int(who))
  File "/Users/user/.virtualenvs/mine/lib/python3.6/site-packages/telethon/telegram_client.py", line 2448, in get_input_entity
    async for dialog in self.get_dialogs(100):
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

**Comment by expectocode** [comment]
Is your telethon the latest version?

**Comment by expectocode** [comment]
Aha, this is actually a telethon bug! I'm going to submit a PR.

**Comment by expectocode** [comment]
Ah, the bug was fixed two days ago but isn't in PyPI yet. 

@Lonami please push :)

**Comment by Lonami** [comment]
https://pypi.python.org/pypi/Telethon-aio/0.18.2.3
