### ISSUE TITLE
TypeError: object TelegramClient can't be used in 'await' expression

### ISSUE THREAD

**Issue by gleehokie** [expectocode/telegram-export#35]
I get a "TypeError: object TelegramClient can't be used in 'await' expression" error when running telegram-export.

```greg$ telegram-export --config-file ~/.config/telegram-export/config.ini
Please enter the code you received: xxxxx
Signed in successfully as Greg Lee
Traceback (most recent call last):
  File "/usr/local/bin/telegram-export", line 4, in <module>
    __import__('pkg_resources').run_script('telegram-export==0.1.3', 'telegram-export')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/telegram_export-0.1.3-py3.6.egg/EGG-INFO/scripts/telegram-export", line 3, in <module>
    __requires__ = 'telegram-export==0.1.3'
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/telegram_export-0.1.3-py3.6.egg/telegram_export/__main__.py", line 294, in <module>
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/telegram_export-0.1.3-py3.6.egg/telegram_export/__main__.py", line 267, in main
TypeError: object TelegramClient can't be used in 'await' expression```

**Comment by Lonami** [comment]
When pasting logs, please use triple backquotes (`\`\`\``). Are you sure you're using `telethon-aio`? If you just installed export this should be the case. You can `pip show telethon-aio` to confirm. `pip show telethon` should show no result.

**Comment by gleehokie** [comment]
I had both telethon-aio and telethon installed.  I uninstalled telethon and am getting somewhere with telegram-export now.

**Comment by Lonami** [comment]
Awesome :) currently they're not compatible (so plugins can work for both versions without worrying about the module name) but they might be in the future!
