### ISSUE TITLE
Having RuntimeError "Number of retries reached 0 for ['GetFileRequest']"

### ISSUE THREAD

**Issue by p05ong** [expectocode/telegram-export#38]
I enabled the media download. I got a lot of "Lost Request" warning at first, then I got this error and the program was stopped.
Does it mean the media is not available any more or cannot download?
```
2018-05-02 18:25:39,746 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<Downloader._media_consumer() done, defined at /usr/local/lib/python3.6/dist-packages/telegram_export/downloader.py:304> exception=RuntimeError("Number of retries reached 0 for ['GetFileRequest'].",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram_export/downloader.py", line 311, in _media_consumer
    bar)
  File "/usr/local/lib/python3.6/dist-packages/telegram_export/downloader.py", line 300, in _download_media
    progress_callback=progress
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py", line 2174, in download_file
    input_location, offset, part_size
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_bare_client.py", line 449, in __call__
    [type(x).__name__ for x in requests]
RuntimeError: Number of retries reached 0 for ['GetFileRequest'].
```

**Comment by Lonami** [comment]
Can you enable debug logging for the external library and provide it to me once it fails again?

**Comment by expectocode** [comment]
LostRequest warnings are expected, they appear even when media downloading is working. We're working on those. The other error looks like a Telethon thing

**Comment by expectocode** [comment]
@p05ong it's hard for us to help you unless you provide us with logs where the error occurs

**Comment by expectocode** [comment]
Closing due to inactivity, reopen if you get this again and please provide logs
