### ISSUE TITLE
unable to run the application : unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by PoloB12** [expectocode/telegram-export#43]
Hi, 

somehow I'm unable to figure out what causes this error :

$ telegram-export
Traceback (most recent call last):
  File "/usr/local/bin/telegram-export", line 3, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 196, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/__main__.py", line 295, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/__main__.py", line 267, in main
    loop=loop
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 196, in __init__
    **kwargs
TypeError: __init__() got an unexpected keyword argument 'loop'

Any ideas ?

**Comment by Lonami** [comment]
The `telethon` package is not compatible with `telethon-aio`, and you should only have one installed. Try `pip uninstall telethon`.

**Comment by expectocode** [comment]
@Lonami not to forget pip install telethon-aio
i might add that this is in the readme ._.

**Comment by PoloB12** [comment]
Ok, pip now shows telethon removed and telethon-aoi installed version is 0.19.0.6

Now i get an import error :

**$ telegram-export
Traceback (most recent call last):
  File "/usr/local/bin/telegram-export", line 3, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 192, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/__init__.py", line 2, in <module>
    from . import formatters, dumper, downloader, exporter
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/formatters/__init__.py", line 4, in <module>
    from .baseformatter import BaseFormatter
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/formatters/baseformatter.py", line 13, in <module>
    from telethon import utils
ImportError: No module named 'telethon'**

**Comment by expectocode** [comment]
@PoloB12 Its aio not aoi

**Comment by PoloB12** [comment]
correct, typo, there is no such thing as telethon-aoi anyway :)

**Comment by expectocode** [comment]
Does 'import telethon' work in interactive Python?

**Comment by PoloB12** [comment]
no, I wouldn't expect it to work either because I just removed it and replaced it with telethon-aio ? It worked before though, I've used it tonight for another project.

**Comment by expectocode** [comment]
@PoloB12 the package telethon-aio should supply the name telethon for importing

**Comment by expectocode** [comment]
@expectocode so something is wrong on your setup if that is not happening

**Comment by PoloB12** [comment]
ok, then I'll have to figure out how to remove that fix my setup, I already thought something was messed up, thanks

**Comment by expectocode** [comment]
Good luck with your problem :)

**Comment by PoloB12** [comment]
thanks  :)

**Comment by PoloB12** [comment]
Fixed, the --list-dialogs options works fine but as soon as I start without any options I run into an error :

ValueError: Could not find the input entity for "-xxxxxxxxxxxxx"

**Comment by expectocode** [comment]
That's odd -  if it's using the same config file for --list-dialogs and normal running, it should be able to find the input entity. The way the input entity finding works is that Telegram requires you to have "seen" the dialog before, so using --list-dialogs ensures you will have "seen" it. Without more information on your config, I can't say for sure what's happening

**Comment by PoloB12** [comment]
`telegram-export --list-dialogs | grep "that entity id"` doesn't show it either

**Comment by expectocode** [comment]
well i guess there is just no dialog with that id?

**Comment by expectocode** [comment]
by the way, for conversation like this you are welcome to join the group <at>expectocode

**Comment by PoloB12** [comment]
sorry, I don't understand, what group ? Also, I don't understand how it finds the dialog id but that dialog doesnt exist ?

**Comment by expectocode** [comment]
Oh, you meant a literal "-xxxx"? You're meant to edit that part of the config file. 

The group is a telegram group with that username
