### ISSUE TITLE
Error on export: ValueError: Could not find the input entity for "-1001132836449"

### ISSUE THREAD

**Issue by SandiDusic** [expectocode/telegram-export#52]
Hi.

When I try to do a basic export (`telegram-export` with the config already set up), I get the python error down below. This is on Manjaro Linux, installed via pip.

```
2018-06-07 02:20:10,835 - exporter - INFO - Saving to /data_mnt/backup/personal data/telegram
2018-06-07 02:20:11,731 - telegram_export.downloader - INFO - Not getting participants since we are not admin.                          
2018-06-07 02:20:12,171 - telegram_export.downloader - INFO - Done. Retrieving full information about 0 missing entities.1 [00:00<?, ? entities/s, chat=example]
entities: 100%|██████████████| 1/1 [00:00<00:00,  2.07 entities/s, chat=example]
media: 0.00B [00:00, ?B/s, chat=example]
2018-06-07 02:20:12,479 - telegram_export.downloader - INFO - Not getting participants since we are not admin.                                     
2018-06-07 02:20:13,437 - telegram_export.downloader - INFO - Done. Retrieving full information about 0 missing entities.          s/s, chat=Telegram Usernames]
entities: 100%|███| 1/1 [00:00<00:00,  1.04 entities/s, chat=Telegram Usernames]
media: 0.00B [00:00, ?B/s, chat=Telegram Usernames]
2018-06-07 02:20:13,440 - exporter - INFO - Closing exporter
Traceback (most recent call last):
  File "/usr/bin/telegram-export", line 3, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/telegram_export/__main__.py", line 295, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/telegram_export/__main__.py", line 279, in main
    await exporter.start()
  File "/usr/lib/python3.6/site-packages/telegram_export/exporter.py", line 74, in start
    self.client):
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 271, in __anext__
    return await self._do_it(self._it.__next__)
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 197, in __next__
    return self._invoke(first_fn, *first_args)
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/usr/lib/python3.6/site-packages/telegram_export/exporter.py", line 36, in get_entities_iter
    async for ent in entities_from_str(client, in_list):
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 271, in __anext__
    return await self._do_it(self._it.__next__)
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 197, in __next__
    return self._invoke(first_fn, *first_args)
  File "/usr/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/usr/lib/python3.6/site-packages/telegram_export/exporter.py", line 20, in entities_from_str
    await yield_(await client.get_input_entity(int(who)))
  File "/usr/lib/python3.6/site-packages/telethon/telegram_client.py", line 2663, in get_input_entity
    .format(peer)
ValueError: Could not find the input entity for "-1001132836449". Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.
```

**Comment by expectocode** [comment]
@SandiDusic Wait, no. The problem is you haven't edited the config.

**Comment by expectocode** [comment]
@SandiDusic You need to edit the whitelist. You're trying to dump a group you've never been in.

**Comment by SandiDusic** [comment]
Oh dear, that was super quick. I had just returned from reading the README more carefully and realizing my issue. I hadn't filled in the whitelist. Thank you for the quick response.

**Comment by Lonami** [comment]
@expectocode perhaps we should catch the error and notify the user about it, instead of exposing Telethon errors (which the user doesn't need to know about). "No user with ID xyz has been found. If you're sure it's in your dialogs please call once before". Should it be done automatically? What if the user entered a completely random ID though? `warnings.warn`?
