### ISSUE TITLE
c.execute("CREATE TABLE User(" sqlite3.OperationalError: near "WITHOUT": syntax error

### ISSUE THREAD

**Issue by vhdm** [expectocode/telegram-export#57]
@Lonami 
@expectocode 

![dd](https://user-images.githubusercontent.com/14149777/41507161-2e200bda-7242-11e8-9602-6be94e4ffc31.png)

**Comment by Lonami** [comment]
Looks like you're using an old version of Sqlite. An easy fix would be to just remove the `WITHOUT` altogether. It's nice to have but not required.

**Comment by vhdm** [comment]
python3.7 telegram-export --config-file ./config.ini
Traceback (most recent call last):
  File "telegram-export", line 3, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/venv/lib/python3.7/site-packages/telegram_export/__main__.py", line 307, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/root/venv/lib/python3.7/site-packages/telegram_export/__main__.py", line 254, in main
    dumper = Dumper(config['Dumper'])
  File "/root/venv/lib/python3.7/site-packages/telegram_export/dumper.py", line 87, in __init__
    version = c.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by Lonami** [comment]
That's #55 which was fixed, not sure if it's on PyPi though.

**Comment by vhdm** [comment]
@Lonami 
sorry i cant find dumper.py file to remove 'WITHOUT' keyword
centos7

**Comment by Lonami** [comment]
Please upgrade with the following command, https://github.com/expectocode/telegram-export/commit/7e0a30c59a0db100fd4cfcb9cbc1f4690b789783 should have fixed it:
```sh
pip install --upgrade git+https://github.com/expectocode/telegram-export@master
```
