### ISSUE TITLE
TypeError: The given session must be a Session instance

### ISSUE THREAD

**Issue by Karasiq** [expectocode/telegram-export#59]
```python
python3 -m telegram_export
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/__main__.py", line 307, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/telegram_export/__main__.py", line 279, in main
    proxy=proxy
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 197, in __init__
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 101, in __init__
    raise TypeError('The given session must be a Session instance.')
TypeError: The given session must be a Session instance.
Exception ignored in: <bound method TelegramBareClient.__del__ of <telethon.telegram_client.TelegramClient object at 0x7f6ac035f5c0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 174, in __del__
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 246, in disconnect
AttributeError: 'TelegramClient' object has no attribute '_user_connected'
```

Can be fixed with 
```python
import telethon.sessions.SQLiteSession
TelegramClient(SQLiteSession(absolute_session_name), ...
```

**Comment by Lonami** [comment]
I need to get around releasing a new Telethon version but there's still some things to clean-up. Can also be fixed by installing master:
```sh
pip install --no-cache --upgrade git+https://github.com/LonamiWebs/Telethon@master
```

**Comment by moeffju** [comment]
@Lonami Following the installation section and then manually upgrading Telethon to master results in the exporter successfully starting and authenticating, but then I receive the error message

```
AttributeError: 'Dialog' object has no attribute 'dialog'
```

when running `--list-dialogs`.

**Comment by Lonami** [comment]
I can look into that after today's exam :)
