### ISSUE TITLE
Process hangs with option --list-dialogs 

### ISSUE THREAD

**Issue by edigiacomo** [expectocode/telegram-export#61]
`telegram-export --list-dialogs` successfully list dialogs but it hangs and I have to send a signal (e.g. CTRL+C) to terminate it.

```
$ python -m telegram_export --config-file config.ini.example --list-dialogs
...
/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/__main__.py:244: RuntimeWarning: coroutine 'TelegramBaseClient.disconnect' was never awaited
  client.disconnect()

^CTraceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/__main__.py", line 317, in <module>
    loop.run_until_complete(task)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1396, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
```

**Comment by edigiacomo** [comment]
I forgot to list the packages version:

```
$ pip freeze
appdirs==1.4.3
async-generator==1.9
pyaes==1.6.1
pyasn1==0.4.3
rsa==3.4.2
telegram-export==0.1.6
Telethon-aio==1.0rc1
tqdm==4.23.4
```

**Comment by Lonami** [comment]
https://github.com/expectocode/telegram-export/commit/3544903e731cde096c8ce9539316660da2cd5a6b should fix this.
