### ISSUE TITLE
Cannot export group chat

### ISSUE THREAD

**Issue by edigiacomo** [expectocode/telegram-export#62]
When trying to export a group chat, the following exception is thrown:

```
$ python -m telegram_export --config-file config.ini.example --context -286200882
2018-06-26 08:39:30,723 - exporter - INFO - Saving to /home/edg/tg-export
Exception ignored in: <bound method AsyncGenerator.__del__ of <async_generator._impl.AsyncGenerator object at 0x7f9c08cd9860>>
Traceback (most recent call last):████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1904.77 entities/s, chat=test group]
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/async_generator/_impl.py", line 324, in __del__
    .format(self._coroutine.cr_frame.f_code.co_name)
RuntimeError: partially-exhausted async_generator 'get_entities_iter' garbage collected
Exception ignored in: <bound method AsyncGenerator.__del__ of <async_generator._impl.AsyncGenerator object at 0x7f9c08183a58>>
Traceback (most recent call last):
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/async_generator/_impl.py", line 324, in __del__
    .format(self._coroutine.cr_frame.f_code.co_name)
RuntimeError: partially-exhausted async_generator 'entities_from_str' garbage collected
2018-06-26 08:39:31,479 - exporter - INFO - Closing exporter
test group: 3 messages [00:00,  7.57 messages/s]/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/exporter.py:63: RuntimeWarning: coroutine 'TelegramBaseClient.disconnect' was never awaited
  self.client.disconnect()
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/__main__.py", line 307, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/__main__.py", line 291, in main
    await exporter.start()
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/exporter.py", line 75, in start
    await self.downloader.start(entity)
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/telegram_export/downloader.py", line 445, in start
    can_get_participants = is_channel and (target.megagroup or
AttributeError: 'Chat' object has no attribute 'megagroup'
Exception ignored in: <bound method tqdm.__del__ of test group: 3 messages [00:00,  6.93 messages/s]>
Traceback (most recent call last):
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/tqdm/_tqdm.py", line 882, in __del__
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1087, in close
  File "/home/edg/src/tg-bck/env/lib/python3.6/site-packages/tqdm/_tqdm.py", line 439, in _decr_instances
  File "/home/edg/src/tg-bck/env/lib64/python3.6/_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x7f9c0811f4f8; to 'tqdm' at 0x7f9c081836a0>
```

I've installed `telethon` from master branch (see #59):

```
$ pip freeze
appdirs==1.4.3
async-generator==1.9
pyaes==1.6.1
pyasn1==0.4.3
rsa==3.4.2
telegram-export==0.1.6
Telethon-aio==1.0rc1
tqdm==4.23.4
```

**Comment by Lonami** [comment]
Looks like a bug in `tqdm`.

**Comment by Lonami** [comment]
No wait that's not it.

**Comment by Lonami** [comment]
Now it's fixed! I hope.
