### ISSUE TITLE
Error when running telegram-export

### ISSUE THREAD

**Issue by azzamsa** [expectocode/telegram-export#98]
Hi.

I've read other issue regarding this. I always run telegram-export with this command successfully, but today, it gives me an errors

```
python3 /home/user/.virtualenvs/global_py3/bin/telegram-export --config-file /home/user/.config/telegram-export/config.ini
```

``` bash
$ python3 /home/user/.virtualenvs/global_py3/bin/telegram-export --config-file /home/user/.config/telegram-export/config.ini
Traceback (most recent call last):
  File "/home/user/.virtualenvs/global_py3/bin/telegram-export", line 2, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/telegram_export/__main__.py", line 316, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/telegram_export/__main__.py", line 288, in main
    proxy=proxy
TypeError: __init__() got an unexpected keyword argument 'loop'
```
I tried to re-install, but no luck.

Thanks

**Comment by Lonami** [comment]
You're either using an old version of `telethon` or have `telethon-sync` installed. Uninstall `telethon-sync` if present and upgrade `telethon` if present.
